name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest

    - name: Run tests
      run: |
        python -m pytest

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=sonarintegration-1 
            -Dsonar.projectKey=sonarintegration-1_1-sonarscanpython
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
      env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


